apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb                # <── UID fijo
    type: postgres
    access: proxy
    isDefault: true
    url: http://n6qiay2n8g.ixn0msalzw.tsdb.cloud.timescale.com
    # NOTA IMPORTANTE: Grafana no soporta variables de entorno en archivos YAML de provisioning.
    # Estos valores deben coincidir con las credenciales definidas en tu archivo .env.
    user: tsdbadmin
    secureJsonData:
      password: fjrmo14pc7mvqz60  # ⚠️ Contraseña del usuario de la base de datos
    jsonData:
      database: tsdb              # ⚠️ Nombre de la base de datos
      sslmode: "require"          # ⚠️ Habilitar SSL para conexiones seguras
      postgresVersion: 1400
      timescaledb: true

